<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simplepoll"
 *
 * Auto generated by Extension Builder 2014-08-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simple Poll',
	'description' => 'An easy to setup and use poll system',
	'category' => 'plugin',
	'author' => 'Alex Bigott / Pixel Ink',
	'author_email' => 'support@pixel-ink.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '1.1.1',
	'constraints' => [
		'depends' => [
			'typo3' => '6.2.0-7.9.99',
		],
		'conflicts' => [
		],
		'suggests' => [
		],
	],
);
