<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simplepoll"
 *
 * Auto generated by Extension Builder 2014-08-01
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Simple Poll',
	'description' => 'An easy to setup and use poll system',
	'category' => 'plugin',
	'author' => 'Alex Bigott',
	'author_email' => 'support@pixel-ink.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.2',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);